<a href="https://colab.research.google.com/github/fabiomartin5/Curso-de-Python-2024/blob/main/introdu%C3%A7%C3%A3opandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

#criar series com uma lista

series1 = pd.Series([1,2,3,4])
series1

0    1
1    2
2    3
3    4
dtype: int64

In [2]:

#index da series
series1.index

RangeIndex(start=0, stop=4, step=1)

In [3]:
#Criar Series com um dict

series2 = pd.Series(
    {
      "a":1,
     "b":2,
     "c":3,
     "d":4
     }
    )
series2

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
#index da Series com dict
series2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [18]:
import pandas as pd

# Definindo as colunas e o caminho do arquivo
cols = ["longitude", "latitude", "housing_median_age", "population", "households", "median_income"]
arquivo = "/content/sample_data/california_housing_test.csv"

# Lendo o arquivo CSV
df = pd.read_csv(arquivo, usecols=cols)

df

# Exibindo as primeiras linhas do arquivo lido

#.head() (cinco primeiros) head.(10) os 10 primeiros

,longitude,latitude,housing_median_age,population,households,median_income
0,-122.05,37.37,27.0,1537.0,606.0,6.6085
1,-118.30,34.26,43.0,809.0,277.0,3.5990
2,-117.81,33.78,27.0,1484.0,495.0,5.7934
3,-118.36,33.82,28.0,49.0,11.0,6.1359
4,-119.67,36.33,19.0,850.0,237.0,2.9375
...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1258.0,607.0,1.1790
2996,-118.14,34.06,27.0,3496.0,1036.0,3.3906
2997,-119.70,36.30,10.0,693.0,220.0,2.2895
2998,-117.12,34.10,40.0,46.0,14.0,3.2708
2999,-119.63,34.42,42.0,753.0,260.0,8.5608

In [26]:
#index, coluna(columns) e shape do dataframe
df.shape

(3000, 6)

In [29]:
#head e info do DF, describe
df.describe()

,longitude,latitude,housing_median_age,population,households,median_income
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.00000,3000.000000
mean,-119.589200,35.63539,28.845333,1402.798667,489.91200,3.807272
std,1.994936,2.12967,12.555396,1030.543012,365.42271,1.854512
min,-124.180000,32.56000,1.000000,5.000000,2.00000,0.499900
25%,-121.810000,33.93000,18.000000,780.000000,273.00000,2.544000
50%,-118.485000,34.27000,29.000000,1155.000000,409.50000,3.487150
75%,-118.020000,37.69000,37.000000,1742.750000,597.25000,4.656475
max,-114.490000,41.92000,52.000000,11935.000000,4930.00000,15.000100

In [8]:
#vamos baixar o dataset dos filmes do james bond
!wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1VhSehwUQBM_j27hbpCJwhnSQYtap0nCF' -O jamesbond.csv

--2024-09-28 19:53:43--  https://drive.google.com/uc?export=download&id=1VhSehwUQBM_j27hbpCJwhnSQYtap0nCF
Resolving drive.google.com (drive.google.com)... 74.125.204.101, 74.125.204.100, 74.125.204.139, ...
Connecting to drive.google.com (drive.google.com)|74.125.204.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1VhSehwUQBM_j27hbpCJwhnSQYtap0nCF&export=download [following]
--2024-09-28 19:53:43--  https://drive.usercontent.google.com/download?id=1VhSehwUQBM_j27hbpCJwhnSQYtap0nCF&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 173.194.174.132, 2404:6800:4008:c1b::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|173.194.174.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1769 (1.7K) [application/octet-stream]
Saving to: ‘jamesbond.csv’

jamesbond.csv       100%[===================>]   1.73K  --.-KB/s    in 0s

2024-09-28 19:53:46 (20.6 MB/s) - ‘jamesbond.csv’ saved [1769/1769]

In [32]:
#ler csv do jamesbond
path_arquivo_bond = "jamesbond.csv"

df = pd.read_csv(
    path_arquivo_bond
)
df

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Film               27 non-null     object
 1   Year               27 non-null     int64
 2   Actor              27 non-null     object
 3   Director           27 non-null     object
 4   Box Office         27 non-null     float64
 5   Budget             27 non-null     float64
 6   Bond Actor Salary  20 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 1.6+ KB

In [36]:

#iloc com um número e uma slice
df.iloc[0]

Film                        Dr. No
Year                          1962
Actor                 Sean Connery
Director             Terence Young
Box Office                   448.8
Budget                         7.0
Bond Actor Salary              0.6
Name: 0, dtype: object

In [38]:
type (df.iloc[0])

pandas.core.series.Series

In [41]:
#colocar o index do DF do bond como o nome do filme ("Film")
df = df.set_index("Film")
df
#ler o CSV e já colocar a coluna como index

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [44]:
df.iloc[0:10]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN

In [49]:
import pandas as pd

# Exemplo de dados (pode ser carregado a partir de um arquivo CSV)
data = {
    "Year": [1962, 1963, 1964, 1965, 1967, 1967, 1969, 1971, 1973, 1974],
    "Actor": ["Sean Connery", "Sean Connery", "Sean Connery", "Sean Connery", "David Niven",
              "Sean Connery", "George Lazenby", "Sean Connery", "Roger Moore", "Roger Moore"],
    "Director": ["Terence Young", "Terence Young", "Guy Hamilton", "Terence Young", "Ken Hughes",
                 "Lewis Gilbert", "Peter R. Hunt", "Guy Hamilton", "Guy Hamilton", "Guy Hamilton"],
    "Box Office": [448.8, 543.8, 820.4, 848.1, 315.0, 514.2, 291.5, 442.5, 460.3, 334.0],
    "Budget": [7.0, 12.6, 18.6, 41.9, 85.0, 59.9, 37.3, 34.7, 30.8, 27.7],
    "Bond Actor Salary": [0.6, 1.6, 3.2, 4.7, float('NaN'), 4.4, 0.6, 5.8, float('NaN'), float('NaN')]
}

# Criando o DataFrame com "Film" como índice
df = pd.DataFrame(data, index=["Dr. No", "From Russia with Love", "Goldfinger", "Thunderball",
                               "Casino Royale", "You Only Live Twice", "On Her Majesty's Secret Service",
                               "Diamonds Are Forever", "Live and Let Die", "The Man with the Golden Gun"])

# Exibindo o DataFrame original com "Film" como índice
print("DataFrame original com 'Film' como índice:")
print(df.head())

# Transformar o índice 'Film' de volta em coluna
df_reset = df.reset_index()

# Exibindo o DataFrame com a coluna "Film" de volta
print("\nDataFrame com 'Film' como coluna:")
print(df_reset.head())

DataFrame original com 'Film' como índice:
                       Year         Actor       Director  Box Office  Budget  \
Dr. No                 1962  Sean Connery  Terence Young       448.8     7.0
From Russia with Love  1963  Sean Connery  Terence Young       543.8    12.6
Goldfinger             1964  Sean Connery   Guy Hamilton       820.4    18.6
Thunderball            1965  Sean Connery  Terence Young       848.1    41.9
Casino Royale          1967   David Niven     Ken Hughes       315.0    85.0

                       Bond Actor Salary
Dr. No                               0.6
From Russia with Love                1.6
Goldfinger                           3.2
Thunderball                          4.7
Casino Royale                        NaN

DataFrame com 'Film' como coluna:
                   index  Year         Actor       Director  Box Office  \
0                 Dr. No  1962  Sean Connery  Terence Young       448.8
1  From Russia with Love  1963  Sean Connery  Terence Young       543.8
2             Goldfinger  1964  Sean Connery   Guy Hamilton       820.4
3            Thunderball  1965  Sean Connery  Terence Young       848.1
4          Casino Royale  1967   David Niven     Ken Hughes       315.0

   Budget  Bond Actor Salary
0     7.0                0.6
1    12.6                1.6
2    18.6                3.2
3    41.9                4.7
4    85.0                NaN

In [52]:
# reset the index to include 'Film' as a column
df = df.reset_index()

In [54]:
#set the index to 'Film'
df2 = df.set_index("level_0") # use the correct column name
df2.head()

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
level_0,,,,,,,
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [55]:
#ler o CSV e já colocar a coluna como index
df_bond = pd.read_csv(path_arquivo_bond, index_col="Film")
df_bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [59]:
#.loc com o nome do index (str)
# .loc using the actual index values (int)
df2.loc[[0]]

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
level_0,,,,,,,
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6

In [60]:
#.loc com uma lista de indexes
df2.loc[[0, 1]]

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
level_0,,,,,,,
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [63]:
#.loc com slice
df2.loc[0:1]

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
level_0,,,,,,,
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [67]:
#.at para acessar e modificar valores
df2.at[1, "Actor"]

'Sean Connery'

In [70]:
#filtrar dataframe pelas linhas onde os atores são: "Sean Connery" ou  "Sir Sean Connery"
serie_bool1 = (df2["Actor"] == "Sean Connery")
serie_bool2 = (df2["Actor"] == "Sir Sean Connery")
serie_bool3 = serie_bool | serie_bool2
serie_bool3

Film
0                                  False
1                                  False
2                                  False
3                                  False
4                                  False
5                                  False
6                                  False
7                                  False
8                                  False
9                                  False
A View to a Kill                   False
Casino Royale                      False
Casino Royale                      False
Diamonds Are Forever                True
Die Another Day                    False
Dr. No                              True
For Your Eyes Only                 False
From Russia with Love               True
GoldenEye                          False
Goldfinger                          True
Licence to Kill                    False
Live and Let Die                   False
Moonraker                          False
Never Say Never Again               True
No Time to Die                     False
Octopussy                          False
On Her Majesty's Secret Service    False
Quantum of Solace                  False
Skyfall                            False
Spectre                            False
The Living Daylights               False
The Man with the Golden Gun        False
The Spy Who Loved Me               False
The World Is Not Enough            False
Thunderball                         True
Tomorrow Never Dies                False
You Only Live Twice                 True
Name: Actor, dtype: bool

In [71]:
# acessar a coluna "Bond Actor Salary" e usar os métodos .mean() , max() , std()
df2['Bond Actor Salary'].mean()
df2['Bond Actor Salary'].max()
df2['Bond Actor Salary'].std()

2.089998860788024

In [72]:
df2['Bond Actor Salary'].median()

3.2

In [73]:

# acessar a coluna "Actor" e usar value_counts()
df2['Actor'].value_counts()

Actor
Sean Connery        5
Roger Moore         2
Sir Sean Connery    1
David Niven         1
George Lazenby      1
Name: count, dtype: int64

In [76]:
#Exercicio de Merge/Join

# Listas de frutas e seus países de origem
frutas = ["Maçã", "Laranja", "Ameixa", "Uva", "Mirtilo", "Melancia"]
paises_frutas = ["Brasil", "Espanha", "Portugal", "Itália", "EUA", "Brasil"]

df_frutas = pd.DataFrame({'Fruta': frutas, 'País': paises_frutas})

esportes = ["Futebol", "Basquete", "Vôlei", "Tênis", "Natação"]
paises_esportes = ["Brasil", "EUA", "Brasil", "França", "EUA"]

# Criando DataFrame de esportes
df_esportes = pd.DataFrame({'Esporte': esportes, 'País': paises_esportes})

In [77]:
#inner join
joined_df = df_esportes.merge(
    df_frutas,
    on="País",
    how="inner"
)
joined_df

    Esporte    País     Fruta
0   Futebol  Brasil      Maçã
1   Futebol  Brasil  Melancia
2     Vôlei  Brasil      Maçã
3     Vôlei  Brasil  Melancia
4  Basquete     EUA   Mirtilo
5   Natação     EUA   Mirtilo

In [78]:
#outer join
joined_df = df_esportes.merge(
    df_frutas,
    on="País",
    how="outer"
)
joined_df

    Esporte      País     Fruta
0   Futebol    Brasil      Maçã
1   Futebol    Brasil  Melancia
2     Vôlei    Brasil      Maçã
3     Vôlei    Brasil  Melancia
4  Basquete       EUA   Mirtilo
5   Natação       EUA   Mirtilo
6     Tênis    França       NaN
7       NaN   Espanha   Laranja
8       NaN  Portugal    Ameixa
9       NaN    Itália       Uva

In [79]:
#groupby Actor
agrupamento_ator = df2.groupby("Actor")
agrupamento_ator.count()

                  index  Year  Director  Box Office  Budget  Bond Actor Salary
Actor
David Niven           1     1         1           1       1                  0
George Lazenby        1     1         1           1       1                  1
Roger Moore           2     2         2           2       2                  0
Sean Connery          5     5         5           5       5                  5
Sir Sean Connery      1     1         1           1       1                  1

In [86]:
# Assuming you have a DataFrame named 'df' and have already performed the groupby operation:

# Group data by 'Actor'
agrupamento_ator = df.groupby('Actor')

# Calculate the mean, max, and count of 'Bond Actor Salary'
salario_medio = agrupamento_ator['Bond Actor Salary'].mean()
salario_maximo = agrupamento_ator['Bond Actor Salary'].max()
contagem_salarios = agrupamento_ator['Bond Actor Salary'].count()

# Check the type of salario_medio
type(salario_medio)

pandas.core.series.Series